version: 2
updates:
  - package-ecosystem: github-actions
    rebase-strategy: "auto"
    directory: "/"
    schedule:
      interval: daily
    groups:
      actions-deps:
        patterns:
          - "*"
